import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import { ReactNode } from 'react'

import './globals.css'


const ins = Instrument_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movies App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  { children }: { children: ReactNode }
) {
  return (
    <html lang="en">
      <body className={ins.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
